### ISSUE TITLE
Error when starting docker-make : declaration of "err" shadows declaration at line 98

### ISSUE THREAD

**Issue by alasserr** [mattermost-plugin-jitsi/mattermost-plugin-jitsi#28]
**Mattermost Version**
/

**Plugin Version**
Lattest (from Git : 7c04448d7e9dd4bc972bc2364e4b816b579b6c8f)

**Describe the issue**
After cloning the project, nothing has been changed on the files, starting ./docker-maker : it stops with this error : 

> Running govet
> env GO111MODULE=off /usr/local/go/bin/go get golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow
> /usr/local/go/bin/go vet ./server/...
> /usr/local/go/bin/go vet -vettool=/go/bin/shadow ./server/...
> # github.com/mattermost/mattermost-plugin-demo/server
> server/plugin.go:104:8: declaration of "err" shadows declaration at line 98
> server/plugin.go:170:8: declaration of "err" shadows declaration at line 98
> make: *** [Makefile:60: govet] Error 2

**Additional context**
I runned the same code a few days ago and everything worked fine. Has "#github.com/mattermost/mattermost-plugin-demo/server" repository changed in between ?

**Comment by arunvc** [comment]
though ./docker-make gives you error,
this works 
```
./docker-make dist

```

**Comment by jespino** [comment]
It depends a bit on the environment, but clearly we should fix the shadowing problem here, I'll make a PR later to fix this. Thanks for the heads up @alasserr
